$(document).ready(function(){
 $("#answer1").hide();
  $("#answer2").hide();
   $("#answer3").hide();
    $("#answer4").hide();
     $("#answer5").hide();
      $("#answer6").hide();
   $("#Hide_All").click(function(){
    $("#answer1").hide();
      $("#answer2").hide();
       $("#answer3").hide();
        $("#answer4").hide();
         $("#answer5").hide();
          $("#answer6").hide();
 });
  $("#Answer1").click(function(){
       $("#answer1").show();
});
  $("#Answer2").click(function(){
       $("#answer2").show();
});
  $("#Answer3").click(function(){
       $("#answer4").show();
});
 $("#Answer4").click(function(){
       $("#answer4").show();
 });
  $("#Answer5").click(function(){
       $("#answer5").show();
  });
  $("#Answer6").click(function(){
       $("#answer6").show();
  });
});
