$(document).ready(function(){
 $("#Hide_All").click(function(){
    $("#answer1").hide();
      $("#answer2").hide();
 });
  $("#Answer1").click(function(){
       $("#answer1").show();
});
  $("#Answer2").click(function(){
       $("#answer2").show();
});
});
